#!/bin/sh
#
# This is part 2 of the ppp-on script. It will perform the connection
# protocol for the desired connection.
#
exec chat -v						\
	TIMEOUT		3				\
	ABORT		'\nBUSY\r'			\
	ABORT		'\nNO ANSWER\r'			\
	ABORT		'\nRINGING\r\n\r\nRINGING\r'	\
	ABORT		'\n+CME ERROR: 100\r'			\
	''		AT				\
	'OK-+++\c-OK'	AT				\
	TIMEOUT		$PPP_ON_TIMEOUT		\
	OK		ATDT$TELEPHONE			\
	CONNECT		''				\

